---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: radarr-downloads
  labels:
    type: local
spec:
  storageClassName: local-path
  capacity:
    storage: 2Ti
  accessModes:
    - ReadWriteOnce
    #- ReadWriteMany
    #- ReadOnlyMany
  hostPath:
    path: /mnt/data1
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: k3d-storage-radarr
  labels:
    type: local
spec:
  storageClassName: local-path
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
    #- ReadOnlyMany
    #- ReadWriteMany
  hostPath:
    path: /srv/k3d/radarr
