---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: nzbget
  name: {{ include "nzbget.fullname" . }}
  namespace: default
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "nzbget.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "nzbget.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          name: nzbget
          env:
            - name: TZ
              value: "Europe/Amsterdam"
            - name: PUID
              value: "1000"
            - name: PGID
              value: "1000"
#           - name: UMASK_SET
#             value: "022"
          volumeMounts:
            - mountPath: "/config"
              name: nzbget-data
            - mountPath: "/downloads"
              name: downloads
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          # resources:
          #   limits:
          #     memory: "64Mi"
          #     cpu: "250m"
      volumes:
        - name: nzbget-data
          persistentVolumeClaim:
            claimName: nzbget-config
        - name: downloads
          persistentVolumeClaim:
            claimName: nzbget-downloads
            #readOnly: true
      restartPolicy: Always
      securityContext: {}
