---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: k3d-storage-nzbget
  labels:
    type: local
spec:
  storageClassName: ""
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /srv/k3d/nzbget
