---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "nzbget.fullname" . }}
  labels:
    {{- include "nzbget.labels" . | nindent 4 }}
  namespace: default
spec:
  type: {{ .Values.service.type }}
  selector:
    {{- include "nzbget.selectorLabels" . | nindent 4 }}
  ports:
    - port: 80
      name: http
      targetPort: 6789
