---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: k3d-storage-jackett
  labels:
    type: local
spec:
  storageClassName: ""
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
    #- ReadOnlyMany
    #- ReadWriteMany
  hostPath:
    path: "/srv/k3d/jackett"
