---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRouteTCP
metadata:
  name: qbittorrent-inbound-tcp
spec:
  entryPoints:
    - torrent-tcp
  routes:
    - match: HostSNI(`*`)
      services:
        - name: qbittorrent
          port: 56881
