---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRouteUDP
metadata:
  name: qbittorrent-inbound-udp
spec:
  entryPoints:
    - torrent-udp
  routes:
  - services:
    - name: qbittorrent
      port: 56881
