---
apiVersion: v1
kind: Service
metadata:
  name: qbittorrent
  namespace: default
spec:
  type: ClusterIP
  selector:
    app: qbittorrent
  ports:
    - port: 56881
      name: torrent-tcp
      targetPort: 56881
    - port: 56881
      name: torrent-udp
      targetPort: 56881
      protocol: UDP
    - port: 80
      name: webui
      targetPort: 8000
