---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRouteTCP
metadata:
  name: plex-inbound
  namespace: plex
spec:
  entryPoints:
    - plex
  routes:
    #- match: Host(`traefik.localhost`,`192.168.0.7`,`sme.lt`) && PathPrefix(`/plex`)
    - match: HostSNI(`*`)
      middlewares: []
      #  - name: strip-prefix-plex
      #    namespace: default
      services:
        - name: plex
          namespace: plex
          port: 32400
