---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: video-collection
  namespace: plex
spec:
  storageClassName: manual
  accessModes:
    - ReadOnlyMany
  resources:
    requests:
      storage: 1Gi
