---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: video-collection
  namespace: plex
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadOnlyMany
  hostPath:
    path: "/mnt/data1"
