#version: "3.7"
#
#services:
#  plex:
#    container_name: plex
#    image: plexinc/pms-docker
#    restart: unless-stopped
#    ports:
#      - "192.168.0.7:32400:32400/tcp"
#      - "192.168.0.7:3005:3005/tcp"
#      - "192.168.0.7:8324:8324/tcp"
#      - "192.168.0.7:32469:32469/tcp"
#      - "192.168.0.7:1900:1900/udp"
#      - "192.168.0.7:32410:32410/udp"
#      - "192.168.0.7:32412:32412/udp"
#      - "192.168.0.7:32413:32413/udp"
#      - "192.168.0.7:32414:32414/udp"
#    environment:
#      - "TZ=Europe/Amsterdam"
#      - "PLEX_CLAIM=claim-kCaPyWSYQAYbN8y9xzzV"
#      - "ADVERTISE_IP=http://192.168.0.7:32400/"
#    hostname: plex
#    volumes:
#      - "./database:/config"
#      - "./temp:/transcode"
#      - "/mnt/data1:/data"
#    networks:
#      plex:
#
#networks:
#  plex:
#    name: plex
#    driver: bridge
---
apiVersion: v1
kind: Namespace
metadata:
  name: plex
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: plex
  name: plex
  namespace: plex
spec:
  replicas: 1
  selector:
    matchLabels:
      app: plex
  template:
    metadata:
      labels:
        app: plex
    spec:
      containers:
      - image: plexinc/pms-docker
        imagePullPolicy: Always
        name: pms-docker
        env:
          - name: TZ
            value: Europe/Amsterdam
          - name: PLEX_CLAIM
            value: claim-MpwA9wRTUws7mdCX6U_t
          - name: ADVERTISE_IP
            value: http://192.168.0.7:32400/
        volumeMounts:
          - mountPath: "/downloads"
            name: video-collection
      restartPolicy: Always
      volumes:
        - name: video-collection
          persistentVolumeClaim:
            claimName: video-collection
            readOnly: true
---
apiVersion: v1
kind: Service
metadata:
  name: plex
  namespace: plex
spec:
  type: ClusterIP
  selector:
    app: plex
  ports:
    - port: 32400
      name: plex
      targetPort: 32400
      #- port: 3005
      #  name: http
      #- port: 8324
      #  name: http
      #- port: 32469
      #  name: http
      #- port: 1900
      #  name: upnp
      #  protocol: UDP
      #- port: 32410
      #  name: http
      #  protocol: UDP
      #- port: 32412
      #  name: http
      #  protocol: UDP
      #- port: 32413
      #  name: http
      #  protocol: UDP
      #- port: 32414
      #  name: http
      #  protocol: UDP
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: video-collection
  namespace: plex
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadOnlyMany
  hostPath:
    path: "/mnt/data1"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: video-collection
  namespace: plex
spec:
  storageClassName: manual
  accessModes:
    - ReadOnlyMany
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: echo
  namespace: plex
spec:
  selector:
    matchLabels:
      app: echo
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: echo
    spec:
      volumes:
        - name: video-collection
          persistentVolumeClaim:
            claimName: video-collection
            readOnly: true
      containers:
      - image: busybox
        name: echo
        volumeMounts:
          - mountPath: "/downloads"
            name: video-collection
        command: ["ping", "127.0.0.1"]
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRouteTCP
metadata:
  name: plex-inbound
  namespace: plex
spec:
  entryPoints:
    - plex
  routes:
    #- match: Host(`traefik.localhost`,`192.168.0.7`,`sme.lt`) && PathPrefix(`/plex`)
    - match: HostSNI(`*`)
      middlewares: []
      #  - name: strip-prefix-plex
      #    namespace: default
      services:
        - name: plex
          namespace: plex
          port: 32400
