---
apiVersion: v1
kind: Service
metadata:
  name: plex
  namespace: plex
spec:
  type: ClusterIP
  selector:
    app: plex
  ports:
    - port: 32400
      name: plex
      targetPort: 32400
      #- port: 3005
      #  name: http
      #- port: 8324
      #  name: http
      #- port: 32469
      #  name: http
      #- port: 1900
      #  name: upnp
      #  protocol: UDP
      #- port: 32410
      #  name: http
      #  protocol: UDP
      #- port: 32412
      #  name: http
      #  protocol: UDP
      #- port: 32413
      #  name: http
      #  protocol: UDP
      #- port: 32414
      #  name: http
      #  protocol: UDP
