---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sonarr-config
spec:
  storageClassName: ""
  volumeName: k3d-storage-sonarr
  accessModes:
    - ReadWriteOnce
    #- ReadOnlyMany
    #- ReadWriteMany
  resources:
    requests:
      storage: 128Mi
