---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sonarr-downloads
spec:
  storageClassName: local-path
  volumeName: sonarr-downloads
  accessModes:
    - ReadWriteOnce
    #- ReadOnlyMany
    #- ReadWriteMany
  resources:
    requests:
      storage: 2Ti
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sonarr-config
spec:
  storageClassName: local-path
  volumeName: k3d-storage-sonarr
  accessModes:
    - ReadWriteOnce
    #- ReadOnlyMany
    #- ReadWriteMany
  resources:
    requests:
      storage: 128Mi
